export const ALL_LANGUAGES = [
  { code: 'en', label: 'English', name: 'English' },
  { code: 'hi', label: 'हिन्दी', name: 'Hindi' },
  { code: 'gu', label: 'ગુજરાતી', name: 'Gujarati' },
  { code: 'mr', label: 'मराठी', name: 'Marathi' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ', name: 'Punjabi' },
  { code: 'bn', label: 'বাংলা', name: 'Bengali' },
  { code: 'ta', label: 'தமிழ்', name: 'Tamil' },
  { code: 'te', label: 'తెలుగు', name: 'Telugu' },
  { code: 'kn', label: 'ಕನ್ನಡ', name: 'Kannada' },
  { code: 'ml', label: 'മലയാളം', name: 'Malayalam' },
  { code: 'or', label: 'ଓଡ଼ିଆ', name: 'Odia' },
  { code: 'as', label: 'অসমীয়া', name: 'Assamese' },
  { code: 'ur', label: 'اردو', name: 'Urdu' },
  { code: 'sa', label: 'संस्कृत', name: 'Sanskrit' },
  { code: 'ks', label: 'كأشُر', name: 'Kashmiri' },
  { code: 'gom', label: 'कोंकणी', name: 'Konkani' },
  { code: 'mai', label: 'मैथिली', name: 'Maithili' },
  { code: 'mni', label: 'মৈতৈলোন্', name: 'Manipuri' },
  { code: 'ne', label: 'नेपाली', name: 'Nepali' },
  { code: 'doi', label: 'डोगरी', name: 'Dogri' },
  { code: 'sat', label: 'ᱥᱟᱱᱛᱟᱲᱤ', name: 'Santali' },
  { code: 'sd', label: 'سنڌي', name: 'Sindhi' },
  { code: 'brx', label: 'बड़ो', name: 'Bodo' }
];
